In [18]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [19]:
import numpy as np

In [20]:
arr = [1, 2, 3, 4, 5]
np_arr = np.array(arr)
print(type(arr))
print(type(np_arr))


<class 'list'>
<class 'numpy.ndarray'>


In [21]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


python의 range함수와 비슷하게 사용 가능

In [22]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
arr = np.arange(25).reshape(5, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


indexing 

In [24]:
print(arr[1][2])

7


In [25]:
#1번 2번행/ 0번, 1번 열
print(arr[1:3, :2])

[[ 5  6]
 [10 11]]


원본배열을 수정하지 않으려면 np.copy()함수를 활용

In [26]:
arr2 = arr
arr2[0][0] = 15
print(arr)
print(arr2)

[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
arr = np.arange(15).reshape(3, 5)
arr2 = arr.copy()
arr2[0][0] = 15
print(arr)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
